### ISSUE TITLE
[BUG] Searching is broken frequently

### ISSUE THREAD

**Issue by BlaztOne** [chaldea-center/chaldea#30]
**Describe the bug**
To be honest, I had tried to search for some servants' names and got this issue multiple times so I decided to report this. Also, change the Japanese name of the fairy knights, from "Fairy Knight X" to "Real name" (Their names are already revealed to players who haven't done LB6).

**To Reproduce**

**Expected behavior**
Searching doesn't do anything. This issue happens frequently.
**Screenshots**
[https://imgur.com/fGue4ir](url)
**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - App Version v1.6.7(670)

**Smartphone (please complete the following information):**
No
 - App Version [e.g. v1.2.3+4]

**Additional context**

**Comment by narumishi** [comment]
It's not doing nothing, but too many servants matched the query.

First, the main reason is search **does not support phrase as one word**. 
In your example, The result will show anyone who match "lu" or "bu" or "fengxian", not "lu bu fengxian". Then, 326 of 335 servants matched "bu" in his name/skill name/skill description/np. (If you use list view, you can see the result count.)

Try use `lu +bu +fengxian`, then only one result. This is explained at https://docs.chaldea.center/search_filter.html#search

Second, I add Chinese Pinyin and Japanese Romaji too when searching. 
This should be excluded in other language maybe.

**Comment by narumishi** [comment]
The words default to use `AND`, so now `lu bu fengxian ` equals to `lu +bu +fengxian`.

And I may not notice this one before:
> Also, change the Japanese name of the fairy knights, from "Fairy Knight X" to "Real name" (Their names are already revealed to players who haven't done LB6).

This is what fandom wiki shows for this servant. Anyway, it is fixed in V2.

**Comment by narumishi** [comment]
Is it safe to close?

**Comment by BlaztOne** [comment]
It used to be "Baobahn Sith" in V2 and now it's "Fairy Knight Tristan"(Both Japanese and English). This is an issue to all fairy knights; Especially when many EoR names which are supposed to be hidden are still shown. Therefore, I think it's fair to change fairy knights names to their real names
[
![image](https://user-images.githubusercontent.com/69741876/164973085-370451fe-f15d-44b2-8442-67dbd9335f81.png)
](url)
[
![image](https://user-images.githubusercontent.com/69741876/164973158-eb415a5d-0d4e-4a80-9038-3bd2b5196e37.png)
](url)

**Comment by narumishi** [comment]
@BlaztOne They are not the same, for fairy knights, the name depends on the their ascension, specifically, only ascension 0 show fairy knights and other ascension levels show true name.

But for servants from 1.5.x, their shown name depends on your main story progress. And the official has been announced their names in notices or anywhere else won't be encrypted anymore(already announced 1~2 years ago in JP), so we always use true names for them.
